In [2]:
print("Hello, World!")

Hello, World!

In [3]:
print("Hello, World!")

Hello, World!

In [4]:
from google.colab import files
uploaded = files.upload()

KeyboardInterrupt:

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('retail_dataset.csv')

In [ ]:
df.head()

In [ ]:
df.info()

In [ ]:
df.isnull().sum()

In [1]:
from google.colab import files
uploaded = files.upload()

Saving retail_dataset.csv to retail_dataset.csv

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('retail_dataset.csv')

In [4]:
df.isnull().sum()

Transaction ID      0
Customer ID         0
Product Category    3
Quantity            2
Price               5
Date                0
Region              2
dtype: int64

In [6]:
df.isnull()

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...
95,False,False,False,False,False,False,False
96,False,False,False,False,False,False,False
97,False,False,False,False,False,False,False
98,False,False,False,False,False,False,False
99,False,False,False,False,False,False,False

In [7]:
df['Quantity'] = df['Quantity'].fillna(df['Quantity'].mean())

In [8]:
df['Quantity']

0      7.0
1      4.0
2      8.0
3      5.0
4      7.0
      ...
95    10.0
96     9.0
97     7.0
98     9.0
99     8.0
Name: Quantity, Length: 100, dtype: float64

In [9]:
df['Price'] = df['Price'].fillna(df['Price'].mean())

In [10]:
df['Price']

0      167.0
1      374.0
2     1059.0
3      304.0
4      282.0
       ...
95    2901.0
96    1077.0
97     643.0
98     429.0
99    1183.0
Name: Price, Length: 100, dtype: float64

In [12]:
df[['Product Category','Region']]

   Product Category Region
0             Books  North
1              Toys  South
2         Furniture  South
3         Groceries  South
4             Books   West
..              ...    ...
95        Furniture  North
96         Clothing  North
97         Clothing  North
98        Groceries  South
99        Furniture  North

[100 rows x 2 columns]

In [15]:
df = df.dropna (subset=['Product Category', 'Region'])

In [17]:
df.shape

(95, 7)

In [19]:
import numpy as np

In [20]:
df['Revenue'] = np.multiply(df['Quantity'], df['Price'])

/tmp/ipykernel_3913/1830166690.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Revenue'] = np.multiply(df['Quantity'], df['Price'])

In [23]:
df.head()

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region,Revenue
0,T001,C015,Books,7.0,167.0,02-02-2023,North,1169.0
1,T002,C004,Toys,4.0,374.0,17-02-2023,South,1496.0
2,T003,C033,Furniture,8.0,1059.0,17-05-2024,South,8472.0
3,T004,C047,Groceries,5.0,304.0,11-02-2024,South,1520.0
4,T005,C022,Books,7.0,282.0,27-07-2024,West,1974.0

In [24]:
Total_Revenue = np.sum(df['Revenue'])
print(Total_Revenue)

465529.66058002145

In [25]:
category_revenue = df.groupby('Product Category')['Revenue'].sum().sort_values(ascending=False)
print(category_revenue)

Product Category
Furniture      129664.526316
Electronics     93204.315789
Clothing        85006.000000
Toys            53947.879699
Sports          34484.000000
Books           29597.938776
Beauty          27647.000000
Groceries       11978.000000
Name: Revenue, dtype: float64

In [26]:
category_revenue = df.groupby('Product Category')['Revenue'].sum().sort_values(ascending=False)

In [27]:
top_3 = category_revenue.head(3)
print(top_3)

Product Category
Furniture      129664.526316
Electronics     93204.315789
Clothing        85006.000000
Name: Revenue, dtype: float64

In [28]:
bottom_3 = category_revenue.tail(3)
print(bottom_3)

Product Category
Books        29597.938776
Beauty       27647.000000
Groceries    11978.000000
Name: Revenue, dtype: float64

In [30]:
region_revenue = df.groupby('Region')['Revenue'].sum().sort_values(ascending=False)
print(region_revenue)

Region
North    153244.353383
East     126232.044039
South    104855.736842
West      81197.526316
Name: Revenue, dtype: float64

In [31]:
highest_region = region_revenue.idxmax()
highest_value = region_revenue.max()
print("Highest Revenue Region:", highest_region, "-", highest_value)

Highest Revenue Region: North - 153244.35338345866

In [32]:
lowest_region = region_revenue.idxmin()
lowest_value = region_revenue.min()
print("Lowest Revenue Region:", lowest_region, "-", lowest_value)

Lowest Revenue Region: West - 81197.52631578947

In [33]:
df['Date'] = pd.to_datetime(df['Date'], dayfirst=True)

/tmp/ipykernel_3913/4183834281.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Date'] = pd.to_datetime(df['Date'], dayfirst=True)

In [34]:
df['Month'] = df['Date'].dt.month

/tmp/ipykernel_3913/2435766877.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Month'] = df['Date'].dt.month

In [35]:
monthly_revenue = df.groupby('Month')['Revenue'].sum()
print(monthly_revenue)

Month
1     43994.000000
2     33028.000000
3     10557.000000
4     57298.526316
5     27915.000000
6     28190.000000
7     47851.292159
8     76958.000000
9     30719.105263
10    38017.000000
11    27662.736842
12    43339.000000
Name: Revenue, dtype: float64

In [36]:
mean_revenue = np.mean(df['Revenue'])
median_revenue = np.median(df['Revenue'])
std_revenue = np.std(df['Revenue'])

print("Mean Revenue:", mean_revenue)
print("Median Revenue:", median_revenue)
print("Standard Deviation of Revenue:", std_revenue)

Mean Revenue: 4900.312216631804
Median Revenue: 3282.1052631578946
Standard Deviation of Revenue: 4721.171795257337